[package]
name = "xtask"
description = "Workspace automation tasks."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
clap.workspace = true
nexa_compiler.workspace = true
nexa_diagnostics.workspace = true
nexa_source.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true

[lints]
workspace = true
