[package]
name = "nexa_parser"
description = "Parser entry points for the Nexa compiler."
version.workspace = true
publish.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true

[dependencies]
nexa_diagnostics.workspace = true
nexa_span.workspace = true
nexa_syntax.workspace = true
rowan.workspace = true

[lints]
workspace = true
